package 예외2;

public class Main {

	public static void main(String[] args) {
		
		int num = 100;
		int divisor = 5;
		try {
			System.out.println(num/divisor);
		} catch (Exception e) {
			// TODO: handle exception
		}
		System.out.println("실행됨?");
		

	}

}
